=== JanKolomaznik/MedV4D/src/Applications/TransferFunctions/TF/TFScheme.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT TFScheme (TFFunction+)>
<!ATTLIST TFScheme name ID #REQUIRED>

<!ELEMENT TFFunction (TFPoint*)>
<!ATTLIST TFFunction
  name ID #REQUIRED
  colourR CDATA "0"
  colourG CDATA "0"
  colourB CDATA "0">

<!ELEMENT TFPoint EMPTY>
<!ATTLIST TFPoint
  x ID #REQUIRED
  y CDATA "0">

=== JanKolomaznik/MedV4D/src/Applications/TransferFunctions/data/scheme1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TFScheme SYSTEM "..\TF\TFScheme.dtd">

<TFScheme name = "scheme1">
	<TFFunction name = "fun1" colourR = "0" colourG = "0" colourB = "0" >
		<TFPoint x = "24" y = "48" />
		<TFPoint x = "32" y = "45" />
		<TFPoint x = "43" y = "58" />
		<TFPoint x = "58" y = "64" />
		<TFPoint x = "68" y = "80" />
		<TFPoint x = "87" y = "80" />
		<TFPoint x = "101" y = "96" />
		<TFPoint x = "120" y = "97" />
		<TFPoint x = "137" y = "111" />
		<TFPoint x = "159" y = "109" />
		<TFPoint x = "169" y = "86" />
		<TFPoint x = "189" y = "92" />
		<TFPoint x = "200" y = "74" />
		<TFPoint x = "217" y = "79" />
		<TFPoint x = "226" y = "65" />
		<TFPoint x = "241" y = "63" />
		<TFPoint x = "254" y = "43" />
		<TFPoint x = "279" y = "47" />
	</TFFunction>
	<TFFunction name = "fun2" colourR = "0" colourG = "0" colourB = "0" >
		<TFPoint x = "71" y = "93" />
		<TFPoint x = "102" y = "175" />
		<TFPoint x = "126" y = "97" />
		<TFPoint x = "145" y = "172" />
		<TFPoint x = "172" y = "107" />
	</TFFunction>
</TFScheme>
